_wandb:
    value:
        cli_version: 0.25.1
        e:
            2ebn3ppb7eagcgzcs82a6qc13ti6fq27:
                codePath: EfficientNet_B0.ipynb
                codePathLocal: EfficientNet_B0.ipynb
                email: umw7eg@virginia.edu
                executable: /apps/software/standard/core/jupyterlab/4.4.6-py3.12/bin/python3.12
                git:
                    commit: b0f8d1a842cb48cf2450f0a82ec510a4d04566f3
                    remote: https://github.com/virginia-vrb9e/isic2019-skin-lesion-classification.git
                host: udc-an28-13
                os: Linux-4.18.0-553.47.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: EfficientNet_B0.ipynb
                python: CPython 3.12.12
                root: /sfs/gpfs/tardis/home/umw7eg/isic2019-skin-lesion-classification/haejin
                startedAt: "2026-04-16T03:11:32.010124Z"
                writerId: 2ebn3ppb7eagcgzcs82a6qc13ti6fq27
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "3":
                - 14
            "4": 3.12.12
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
freeze_bb:
    value: true
loss_fn:
    value: ce
