default:
	@cat makefile

minitest:
	. ~/env/bin/activate; python rn50_base_va.py --data_dir ~/dpy8wq/isic2019/ISIC_2019_mini_folder --num_epochs 2 --mini_run

wandtest:
	. ~/env/bin/activate; python rn50_base_va.py --data_dir ~/dpy8wq/isic2019/ISIC_2019_mini_folder --num_epochs 2 --mini_run --wandb

fulltest2:
	. ~/env/bin/activate; python rn50_base_va.py --data_dir ~/dpy8wq/isic2019/ISIC_2019_mini_folder --num_epochs 2
